chore: Check Prettier formatting in CI (#590)
* chore: Check Prettier formatting in CI

* chore: Update PNPM & pin Prettier version

* chore: Simplify print logic

* chore: Fix path to Prettier

* chore: Use PNPM 9.5.0

* chore: Revert to PNPM 9.1.1

* chore: Remove SHA-1

* chore: Trying PNPM 9.2

* chore: Testing PNPM 9.3

* chore: Capture & mirror exit code from Prettier

* chore: Revert to PNPM 9.1.1

* chore: Printing output

* chore: Tryin' stuff

* chore: Simplify

* chore: No need to run scripts for formatting checks

* chore: Trying to capture exit code

* chore: No explicit exit

* chore: Does GHA set -e?

* chore: Aha!

* chore: Improve annotations

* chore: Fix interpolation

* chore: Fix formatting

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -72,6 +72,33 @@ jobs:
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
+  check-formatting:
+    name: Check formatting
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
+      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
+      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
+        with:
+          node-version-file: .node-version
+          cache: pnpm
+      - name: Install dependencies
+        run: pnpm install --ignore-scripts --frozen-lockfile
+      - name: Check formatting
+        run: |
+          set +e # Allow Prettier to fail, but capture the error code
+          output=$(./node_modules/.bin/prettier --list-different ./packages/nuqs 2>&1)
+          exit_code=$?
+          set -e
+          if [ $exit_code -ne 0 ]; then
+            echo "$output" | while IFS= read -r file; do
+              echo "::warning file=$file::Prettier detected formatting issues in $file"
+            done
+            exit $exit_code
+          else
+            echo "No formatting issues found"
+          fi
+
   cd:
     name: Deployment
     runs-on: ubuntu-latest
